# Generated by Django 4.2.11 on 2025-03-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='due_month',
        ),
    ]
